### ISSUE TITLE
Encoding issue for lines starting with a dot

### ISSUE THREAD

**Issue by arjan** [archaelus/esmtp#1]
esmtp does not insert a leading dot for every line that begins with a dot. I've quoted the RFC below.

See Section 4.5.2 of RFC 2821

```
* Before sending a line of mail text, the SMTP client checks the
  first character of the line. If it is a period, one additional
  period is inserted at the beginning of the line.

* When a line of mail text is received by the SMTP server, it checks
  the line. If the line is composed of a single period, it is
  treated as the end of mail indicator. If the first character is a
  period and there are other characters on the line, the first
  character is deleted.
```

**Comment by mworrell** [comment]
We made a fix in: http://code.google.com/p/zotonic/source/detail?r=f88dd1da65168b73ad992b1be00cc5343b2419b5

**Comment by archaelus** [comment]
This still isn't fixed in esmtp - z_convert doesn't exist, so I can't just apply that.

Possibly the low level API should just pass through the message body as is and assume the upper layer has already fixed it for us. We already assume that email addresses are correctly angle-bracketed too. A convenience API on top of this that escapes "."s and angle-brackets email addresses is a must I guess.

**Comment by mworrell** [comment]
We found that the fix didn't work when we use exim4 as the mailer.  So now we just do a quoted-printable encode of all dots as well.  Which solves the problem regardless of mailer or gateway.
